### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mitoskalandiel**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/smeierzubiesen/Fasetto.Word/pull/14%23issuecomment-335041543%22%2C%20%22https%3A//github.com/smeierzubiesen/Fasetto.Word/pull/14%23issuecomment-335041587%22%2C%20%22https%3A//github.com/smeierzubiesen/Fasetto.Word/pull/14%23issuecomment-335041700%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/smeierzubiesen/Fasetto.Word/pull/14%23issuecomment-335041543%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22there%20are%20no%20real%20code%20changes%20here%2C%20just%20the%20Readme.md%20has%20been%20added%20to%20the%20solution%20and%20then%20got%20some%20badges%20added%22%2C%20%22created_at%22%3A%20%222017-10-08T21%3A55%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/8307871%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mitoskalandiel%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-10-08T21%3A56%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/16465551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/smeierzubiesen%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReviewed%202%20of%202%20files%20at%20r1.%5CnReview%20status%3A%20all%20files%20reviewed%20at%20latest%20revision%2C%20all%20discussions%20resolved.%5Cn%5Cn---%5Cn%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/smeierzubiesen/fasetto.word/14%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222017-10-08T21%3A58%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/16465551%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/smeierzubiesen%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/smeierzubiesen%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/16465551%3Fv%3D4%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/smeierzubiesen'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/smeierzubiesen/Fasetto.Word/pull/14#issuecomment-335041543'>General Comment</a></b>
- <a href='https://github.com/mitoskalandiel'></a> there are no real code changes here, just the Readme.md has been added to the solution and then got some badges added
- <a href='https://github.com/smeierzubiesen'></a> :shipit:
- <a href='https://github.com/smeierzubiesen'></a> Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/smeierzubiesen/fasetto.word/14)*

<a href='https://www.codereviewhub.com/smeierzubiesen/Fasetto.Word/pull/14?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/smeierzubiesen/Fasetto.Word/pull/14?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/smeierzubiesen/Fasetto.Word/pull/14?approve=0'></a>&nbsp;<a href='https://github.com/smeierzubiesen/Fasetto.Word/pull/14'></a>
<a href='#crh-end'></a>

---
This change is [Reviewable](https://reviewable.io/reviews/smeierzubiesen/fasetto.word/14)

***
***
***

### CODE REVIEW

**Comment by smeierzubiesen** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/smeierzubiesen/Fasetto.Word/pull/14'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by mitoskalandiel** [comment]
there are no real code changes here, just the Readme.md has been added to the solution and then got some badges added

**Comment by smeierzubiesen** [comment]
:shipit:

**Comment by smeierzubiesen** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/smeierzubiesen/fasetto.word/14)*

**Pull request merged**
